<VideoPl>
    MDBoxLayout:
        orientation: "vertical"
        MDToolbar:
            title: "Project Details"
            right_action_items: [["home", lambda x: app.root.change_screen("filemanager")]]
            left_action_items:[["backburger", lambda x:app.root.change_screen("home")]]
        BoxLayout:
            orientation:"vertical"
            VideoPlayer:
                source:"https://www.dropbox.com/s/0x2ke57h7wv49ll/Sample_512x288.mp4"